import Navbar from "@/components/layout/navbar";
import "./globals.css";
import React from "react";
import { Inter } from "next/font/google";
// import AuthContextProvider from "@/context";
import { WagmiClient, chains } from "@/context/wagmiClient";
import { RainbowKitProvider } from "@rainbow-me/rainbowkit";
import SecLayout from "./secLayout";
import AuthContextProvider from "@/context";



const interFonts = Inter({
    subsets: ["latin"],
    weight: ["200", "400", "500", "600", "700", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

    return (
        <html lang="en">
            <body className={interFonts.className}>
                <AuthContextProvider>
                    <SecLayout>
                    <div className="mb-24">
                        <Navbar />
                    </div>
                    <div>{children}</div>
                    </SecLayout>
                </AuthContextProvider>
            </body>
        </html>
    );
}
